### ISSUE TITLE
Filtering by charts

### ISSUE THREAD

**Issue by Goudah** [fulcrumapp/geojson-dashboard#12]
IS there a way of enhancing functionality of the app through connecting the chart to the map by allowing features to be filtered through chart click?

**Comment by bmcbride** [comment]
This is probably possible but not something I plan on implementing any time soon. This project needs a thorough update to upgrade to the latest Leaflet/Bootstrap versions and I'd probably replace the C3 charts with a more actively developed charting library. I don't currently have the time to devote to this at the moment, but maintainers and PR's are always welcome!
