### ISSUE TITLE
Trying to Get This Think to Work

### ISSUE THREAD

**Issue by perchslayer** [fulcrumapp/geojson-dashboard#9]
I created my own public data set which is here. [ http://bl.ocks.org/d/923a2b36bb6702662667 ]

When I created a map for it using the template, it would not load. So I looked carefully at the parameters expected and indeed it seems your data set has a unique ID for each and every point feature that mine does not have. And since it is required for the tools, I am guessing this is my "main" problem. Could you tell me how you assigned those? And can they be just an integer? Or is this something that the Gist thingy does?

**Comment by rylincoln** [comment]
are you asking about the "fulcrum_id" field?  Those are generated by the database system where the example data source is stored in his example.  it's a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) - probably generated using the database function uuid_generate so each time a record is added it generates a UUID.  I think it just has to be unique - datatype shouldn't matter.
